'?':
    value: false
_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.2
        t:
            "1":
                - 1
                - 55
                - 77
            "2":
                - 1
                - 55
                - 77
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.2
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
alsologtostderr:
    value: false
batch_size:
    value: 2
cuda_device_number:
    value: null
data_path:
    value: datasets/WaterDropSample/
help:
    value: false
helpfull:
    value: false
helpshort:
    value: false
helpxml:
    value: false
log_dir:
    value: ""
logtostderr:
    value: false
lr_decay:
    value: 0.1
lr_decay_steps:
    value: 5000000
lr_init:
    value: 0.0001
mode:
    value: train
model_file:
    value: null
model_path:
    value: models/
n_gpus:
    value: 1
noise_std:
    value: 0.00067
nsave_steps:
    value: 5000
ntraining_steps:
    value: 100
only_check_args:
    value: false
output_filename:
    value: rollout
output_path:
    value: rollouts/
pdb:
    value: false
pdb_post_mortem:
    value: false
profile_file:
    value: null
run_with_pdb:
    value: false
run_with_profiling:
    value: false
showprefixforinfo:
    value: true
stderrthreshold:
    value: fatal
train_state_file:
    value: train_state.pt
use_cprofile_for_profiling:
    value: true
v:
    value: 0
validation_interval:
    value: null
verbosity:
    value: 0
wandb_sweep:
    value: false
